#!/usr/bin/env python3
"""
Build a 2x2 comparison figure of experimental vs synthetic TFM B-scans,
with and without a defect.

  Top row:     experimental — raw FMC from DATA/1D Raw Data/*.mat run
               through the *same* reconstruct_tfm() pipeline as synthetic
  Bottom row:  synthetic — generated by calling run_engine.scan_volume_3d()

  Left column:   grain noise only
  Right column:  with a cylindrical defect (side-drilled hole)

Both rows are dB, normalised to each frame's peak, and displayed on the
same [DB_FLOOR, 0] range — so intensity differences are physically
meaningful.
"""

import os
import sys
import shutil
import numpy as np
import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from engine.config import (
    SimulationConfig, SpecimenConfig, ArrayConfig, AcquisitionConfig,
    ScanPlanConfig,
)
from engine.geometry import Specimen3D, CylindricalDefect
from engine.materials import ALUMINUM
from engine.microstructure import generate_grain_structure, embed_geometric_defects

# Use scan_volume_3d() directly — no re-implementation of the pipeline.
from run_engine import scan_volume_3d, reconstruct_tfm, apply_bandpass_filter

# Project-root Filter (same one used in PROCESSING/Report Filtering Example.py)
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from Classes.Filter import filter_signal

# ── PARAMETERS ───────────────────────────────────────────────────────
# Raw FMC .mat files (same captures the .png TFM images were built from)
EXP_GRAIN_MAT  = ('../DATA/1D Raw Data/Al Pure 10MHz 17022026/Al_70_1_1.mat')
EXP_DEFECT_MAT = ('../DATA/1D Raw Data/Al Hole Diag 15MHz 11022026/Al_40_6.mat')

# Specimen thickness of the experimental blocks (used for TFM z-range)
EXP_GRAIN_THICK  = 70e-3   # "Al_70_*" → 70 mm
EXP_DEFECT_THICK = 40e-3   # "Al_40_*" → 40 mm

OUTPUT = 'output/plots/experimental_vs_synthetic.png'

# Array and specimen — 128 elements @ 0.3 mm pitch (same 38.4 mm aperture
# as scan_3d's 64 @ 0.6 mm)
FREQUENCY       = 10e6
N_ELEMENTS      = 128
ELEMENT_PITCH   = 0.3e-3
SPECIMEN_THICK  = 65e-3
SPECIMEN_WIDTH  = 40e-3
SPECIMEN_DEPTH  = 1.5e-3        # y-axis — only theta=0 slice used, keep thin

# Cylindrical defect (side-drilled hole)
DEFECT_Z        = 15e-3
DEFECT_X        = 0.0
DEFECT_RADIUS   = 1.0e-3

# Grain structure — fine grains (Al 6061-T6 range), well below the PSF
# so we're in fully-developed-speckle (Rayleigh) regime at 10 MHz.
MEAN_GRAIN_SIZE = 0.1e-3        # 100 µm — mid-range wrought Al 6061-T6
VOXEL_SIZE      = 0.050e-3      # 50 µm (~2 voxels per grain)
Z_VARIATION     = 0.025 
C_VARIATION     = 0.005

TFM_Z_START     = 0e-3
TFM_Z_END       = SPECIMEN_THICK - 5e-3
TFM_N_PIXELS    = 800
BORN_THRESHOLD  = 0.015         # raised to cap scatterer count with finer voxels
DB_FLOOR        = -20
# ─────────────────────────────────────────────────────────────────────


def run_scan(with_defect: bool, tag: str) -> np.ndarray:
    """
    Build the grain volume, call scan_volume_3d() with a single frame at
    theta=0, then load and return the resulting dB B-scan.
    """
    print(f"\n{'='*60}\n  Running scan_volume_3d() — {tag}\n{'='*60}")

    specimen = Specimen3D(
        thickness=SPECIMEN_THICK,
        width=SPECIMEN_WIDTH,
        depth=SPECIMEN_DEPTH,
    )

    # Voxel world: grain structure + embedded defects
    grain_vol = generate_grain_structure(
        thickness=specimen.thickness,
        width=specimen.width,
        depth=specimen.depth,
        background_material=ALUMINUM,
        mean_grain_size_m=MEAN_GRAIN_SIZE,
        impedance_variation=Z_VARIATION,
        wavespeed_variation=C_VARIATION,
        voxel_size_m=VOXEL_SIZE,
    )

    defects_to_embed = []
    if with_defect:
        defects_to_embed.append(
            CylindricalDefect(
                center_z=DEFECT_Z,
                center_x=DEFECT_X,
                radius=DEFECT_RADIUS,
                y_start=-specimen.depth / 2,
                y_end=specimen.depth / 2,
            )
        )
    voxel_volume = embed_geometric_defects(grain_vol, defects_to_embed)

    # Single-frame scan plan at theta = 0
    scan_plan = ScanPlanConfig(n_scans=1, theta_start=0.0, theta_end=0.0)

    cfg = SimulationConfig(
        specimen=SpecimenConfig(
            thickness=specimen.thickness,
            width=specimen.width,
        ),
        array=ArrayConfig(
            num_elements=N_ELEMENTS,
            element_pitch=ELEMENT_PITCH,
            frequency=FREQUENCY,
        ),
        acquisition=AcquisitionConfig(),
        scan_plan=scan_plan,
        max_bounces=2,
        mode_conversion=False,
    )

    output_dir = os.path.join(
        os.path.dirname(__file__), 'output', 'comparisons', f'compare_tmp_{tag}'
    )
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)

    # scan_volume_3d's defects_3d stays empty — defects are already embedded
    # in the voxel volume, Born scattering handles both.
    scan_volume_3d(
        specimen=specimen,
        defects_3d=[],
        cfg=cfg,
        scan_plan=scan_plan,
        output_dir=output_dir,
        voxel_volume=voxel_volume,
        born_threshold=BORN_THRESHOLD,
        tfm_z_start=TFM_Z_START,
        tfm_z_end=TFM_Z_END,
        tfm_n_pixels=TFM_N_PIXELS,
    )

    # Load the single saved frame
    bscan_path = os.path.join(output_dir, 'bscan_0000.npy')
    img_db = np.load(bscan_path).astype(np.float32)
    print(f"  Loaded {bscan_path}  shape={img_db.shape}  "
          f"range=[{img_db.min():.1f}, {img_db.max():.1f}] dB")
    return img_db


def _remove_spikes(signal: np.ndarray, threshold: float = 500.0) -> np.ndarray:
    """Replace samples above threshold with the previous sample."""
    out = signal.copy()
    for i in range(1, len(out)):
        if out[i] > threshold:
            out[i] = out[i - 1]
    return out


def load_experimental_tfm(mat_path: str, specimen_thickness: float,
                           tag: str) -> tuple:
    """
    Load a raw FMC .mat file, apply the same bandpass filter used on the
    synthetic data, build the (n_el, n_el, n_t) FMC cube, run it through
    reconstruct_tfm(), and return (img_db, extent).

    Returns
    -------
    img_db : (n_pix, n_pix) float32 — dB, peak-normalised per frame
    extent : [xmin, xmax, zmax, zmin] in mm, ready for matplotlib imshow
    """
    print(f"\n{'='*60}\n  Loading experimental {tag}\n  {mat_path}\n{'='*60}")

    with h5py.File(mat_path, 'r') as f:
        centre_freq = float(f['exp_data/array/centre_freq'][()][0][0])
        el_x        = np.array(f['exp_data/array/el_x1']).flatten()
        tx          = np.array(f['exp_data/tx']).flatten().astype(int)
        rx          = np.array(f['exp_data/rx']).flatten().astype(int)
        time        = np.array(f['exp_data/time'])[0]
        time_data   = np.array(f['exp_data/time_data'])

    n_el = len(el_x)
    n_t  = time_data.shape[1]
    dt   = float(time[1] - time[0])
    print(f"  n_el={n_el}  n_t={n_t}  fc={centre_freq/1e6:.1f} MHz  "
          f"fs={1/dt/1e6:.1f} MHz")

    # Spike removal (copied from PROCESSING/Report Filtering Example.py)
    time_data = np.apply_along_axis(_remove_spikes, axis=1, arr=time_data)

    # Bandpass filter (±60% around centre frequency, matches synthetic)
    f_mhz      = centre_freq / 1e6
    half_bw    = f_mhz * 0.6 / 2
    f_start_Mhz = max(0.1, f_mhz - half_bw)
    f_end_Mhz   = f_mhz + half_bw
    print(f"  Bandpass {f_start_Mhz:.2f}–{f_end_Mhz:.2f} MHz")
    time_data = np.apply_along_axis(
        filter_signal, axis=1, arr=time_data,
        dt=dt, f_start=f_start_Mhz, f_end=f_end_Mhz,
        filter_alpha=1.0, hanning_bool=False,
    ).astype(np.float32)

    # Build (n_el, n_el, n_t) FMC cube
    fmc = np.zeros((n_el, n_el, n_t), dtype=np.float32)
    for t in range(1, n_el + 1):
        mask = tx == t
        data_t = time_data[mask, :]
        rx_t   = rx[mask]
        order  = np.argsort(rx_t)
        fmc[t - 1, :, :] = data_t[order, :]

    # Gate out front-wall echo (same 2 µs gate as synthetic)
    gate_samples = int(2e-6 / dt)
    fmc[:, :, :gate_samples] = 0.0

    # Reconstruct TFM — same pipeline as synthetic
    half_w = (el_x.max() - el_x.min()) / 2
    z_start = TFM_Z_START
    z_end   = specimen_thickness - 5e-3
    print(f"  TFM: x=[{-half_w*1e3:.1f}, {half_w*1e3:.1f}] mm, "
          f"z=[{z_start*1e3:.1f}, {z_end*1e3:.1f}] mm")

    img, x_img, z_img = reconstruct_tfm(
        fmc, time.astype(np.float32), el_x.astype(np.float32),
        ALUMINUM.c_L,
        x_range=(-half_w, half_w),
        z_range=(z_start, z_end),
        n_pixels=TFM_N_PIXELS,
    )

    # Convert to dB — same normalisation as run_engine's 'complex' branch
    img_env = np.abs(img)
    img_db  = 20 * np.log10(img_env / (img_env.max() + 1e-10) + 1e-10)
    img_db  = img_db.astype(np.float32)

    extent = [-half_w * 1e3, half_w * 1e3, z_end * 1e3, z_start * 1e3]
    print(f"  Loaded  shape={img_db.shape}  "
          f"range=[{img_db.min():.1f}, {img_db.max():.1f}] dB")
    return img_db, extent


# =====================================================================
# Main
# =====================================================================

exp_grain,  exp_grain_ext  = load_experimental_tfm(
    EXP_GRAIN_MAT,  EXP_GRAIN_THICK,  'grain')
exp_defect, exp_defect_ext = load_experimental_tfm(
    EXP_DEFECT_MAT, EXP_DEFECT_THICK, 'defect')

syn_grain  = run_scan(with_defect=False, tag='grain')
syn_defect = run_scan(with_defect=True,  tag='defect')

# ── Figure ──
fig, axes = plt.subplots(2, 2, figsize=(11, 10))

axes[0, 0].imshow(exp_grain, cmap='viridis',
                   vmin=DB_FLOOR, vmax=0, aspect='equal', extent=exp_grain_ext)
axes[0, 0].set_title('Experimental — grain noise only\n'
                      '(Al Pure, 10 MHz)', fontsize=11)
axes[0, 0].set_xlabel('x (mm)')
axes[0, 0].set_ylabel('z (mm)')

axes[0, 1].imshow(exp_defect, cmap='viridis',
                   vmin=DB_FLOOR, vmax=0, aspect='equal', extent=exp_defect_ext)
axes[0, 1].set_title('Experimental — with defect\n'
                      '(Al Hole Diag, 15 MHz)', fontsize=11)
axes[0, 1].set_xlabel('x (mm)')
axes[0, 1].set_ylabel('z (mm)')

half_w_mm = (N_ELEMENTS * ELEMENT_PITCH) / 2 * 1e3
syn_extent = [-half_w_mm, half_w_mm, TFM_Z_END * 1e3, TFM_Z_START * 1e3]

axes[1, 0].imshow(syn_grain, cmap='viridis',
                   vmin=DB_FLOOR, vmax=0, aspect='equal', extent=syn_extent)
axes[1, 0].set_title(f'Synthetic — grain noise only\n'
                      f'(Al, {FREQUENCY/1e6:.0f} MHz, '
                      f'{N_ELEMENTS} elements)', fontsize=11)
axes[1, 0].set_xlabel('x (mm)')
axes[1, 0].set_ylabel('z (mm)')

im3 = axes[1, 1].imshow(syn_defect, cmap='viridis',
                         vmin=DB_FLOOR, vmax=0, aspect='equal', extent=syn_extent)
axes[1, 1].set_title(f'Synthetic — with cylindrical defect\n'
                      f'(r = {DEFECT_RADIUS*1e3:.1f} mm at '
                      f'z = {DEFECT_Z*1e3:.0f} mm)', fontsize=11)
axes[1, 1].set_xlabel('x (mm)')
axes[1, 1].set_ylabel('z (mm)')

cbar_ax = fig.add_axes([0.25, 0.04, 0.5, 0.015])
cb = fig.colorbar(im3, cax=cbar_ax, orientation='horizontal')
cb.set_label('TFM amplitude (dB, peak-normalised per frame)', fontsize=9)
cb.ax.tick_params(labelsize=8)

fig.suptitle('Experimental vs Synthetic TFM B-scans', fontsize=14, y=0.98)
plt.tight_layout(rect=[0, 0.08, 1, 0.96])
plt.savefig(OUTPUT, dpi=200, bbox_inches='tight')
print(f"\nSaved → {OUTPUT}")
